behaviors:
  Rabbit:
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 256
    max_steps: 5.0e9
    trainer_type: ppo
environment_parameters:
  spawn_amount:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 200
        value: 100
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 90
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 80
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 70
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 60
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 50
      - name: Lesson6
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 40
      - name: Lesson7
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 30  
      - name: Lesson8
        completion_criteria:
          measure: reward
          behavior: Male Rabbit
          signal_smoothing: true
          min_lesson_length: 25
          threshold: 100
        value: 20

